import { quick, units } from "./pack.js";

const C = "ChatGPT";
const S = "desk";
const t = (spec) => quick({ brand: C, scene: S, ...spec });

const vs = t({
  id: "vs",
  title: "A fondo no es el ChatGPT del día a día",
  blurb: "12 lecciones, 4 horas: trabajo estratégico, varios pasos, investigación.",
  hooks: [
    "Coursiv separa ChatGPT (13 lecciones, 6 horas: lluvia de ideas, respuestas rápidas, ayuda diaria) de ChatGPT: A fondo (12 lecciones, 4 horas).",
    "Aquí el chat no es un soplo. Es un sistema de varios pasos: investigar, partir, redactar, revisar.",
  ],
  idea: "Si el pedido es un mail o una lista, el curso corto alcanza. Si hay investigación, un pipeline y una decisión, estás en A fondo.",
  bullets: [
    "Varios pasos, no un solo globo",
    "Investigación con recorte y fuente",
    "Trabajo estratégico: hay un dueño y un entregable",
    "El día a día se queda en el otro curso",
  ],
  q: "¿Cuándo A fondo y no el ChatGPT diario?",
  opts: ["Para el sticker", "Cuando hay varios pasos e investigación", "Siempre", "Nunca, son lo mismo"],
  ans: 1,
  why: "Coursiv los lista aparte porque el oficio cambia.",
  fillTitle: "Elige el cajón",
  fillLead: "Diario vs sistema.",
  template: "El mail del cliente va al {blank}. El pipeline de investigación va a {blank}. No los {blank}.",
  answers: ["ChatGPT diario", "A fondo", "mezcles en un soplo"],
  slots: ["corto", "sistema", "error"],
  sim: "Oficios partidos. A fondo no es el chat de los stickers.",
  rq: "¿A fondo tiene más horas que el ChatGPT diario?",
  ropts: ["Sí, 6 vs 4", "No: 4 horas vs 6 del diario. Es más denso, no más largo", "Son iguales"],
  rans: 1,
  rwhy: "Coursiv: diario 6 h / 13 caps. A fondo 4 h / 12 caps.",
  tip: "varios pasos e investigación. El resto, el otro curso.",
  items: ["12 lecciones, 4 horas", "Estratégico, no diario", "No mezclar oficios"],
});

const pasos = t({
  id: "pasos",
  title: "Tareas de varios pasos, en voz alta",
  blurb: "Parte, cruza, redacta, revisa. Un chat no es un pipeline si lo mezclas.",
  hooks: [
    "“Hazme el reporte” es un soplo. “1) extrae, 2) cruza, 3) redacta 1 página, 4) lista huecos” es un sistema.",
    "Coursiv pone “tareas de varios pasos” en este curso por eso: el modelo se pierde si le pides el universo.",
  ],
  idea: "Numera los pasos. Un entregable por paso. No pidas el ensayo en el paso 1. Tú pegas la salida de uno como entrada del siguiente si hace falta.",
  bullets: [
    "Pasos numerados",
    "Un entregable por paso",
    "No mezclar investigación y copy en el mismo soplo",
    "Revisión al final, no al inicio",
  ],
  q: "¿Qué convierte un chat en pipeline?",
  opts: ["Más emojis", "Pasos numerados con un entregable cada uno", "Cambiar de modelo a cada renglón", "Pedir “sé estratégico”"],
  ans: 1,
  why: "El número obliga a no saltarse el cruce.",
  fillTitle: "Numera el oficio",
  fillLead: "Cuatro pasos.",
  template: "1) {blank}. 2) {blank}. 3) {blank}. 4) lista huecos.",
  answers: ["extrae la tabla", "cruza con la meta", "redacta una página"],
  slots: ["p1", "p2", "p3"],
  sim: "Pipeline listo. El copy espera al cruce. Los huecos van al final.",
  rq: "¿Por qué no pedir el ensayo en el paso 1?",
  ropts: ["Porque queda feo", "Porque aún no cruzaste: el ensayo inventa el hueco", "Por tokens"],
  rans: 1,
  rwhy: "El orden es el producto.",
  tip: "numera. Un entregable por paso.",
  items: ["Parte", "Cruza", "Redacta", "Revisa"],
});

const projects = t({
  id: "projects",
  title: "Projects como sistema, no como carpeta",
  blurb: "Instrucciones, archivos y el hilo del caso. El chat suelto se pierde.",
  hooks: [
    "A fondo se sostiene en un Project: el brief vive. El chat de marzo no es un sistema.",
    "Reglas arriba. Archivos del caso, no de toda la empresa.",
  ],
  idea: "Un Project por tipo de trabajo (research comercial, reportes, propuestas). Knowledge = lo de esta temporada. El hilo se pega encima.",
  bullets: [
    "Reglas al inicio",
    "Archivos del caso",
    "Un Project ≠ mil chats",
    "El hilo viejo no es el archivo",
  ],
  q: "¿Dónde viven las reglas de “no inventar cifras”?",
  opts: ["Al final del prompt", "En las instrucciones del Project", "En un tweet", "Nunca"],
  ans: 1,
  why: "Si van al final, ya escribió con cifras sueltas.",
  fillTitle: "Arma el Project",
  fillLead: "Nombre, veda, archivo.",
  template: "Project {blank}. Nunca {blank}. Archivos: {blank}.",
  answers: ["research Q3", "inventar cifras", "el brief de esta semana"],
  slots: ["nombre", "veda", "knowledge"],
  sim: "Project listo. La veda está arriba. El brief es el de esta semana.",
  rq: "¿Pegas los PDFs de 2019 “por contexto”?",
  ropts: ["Sí", "No: el caso de ahora + el molde", "Sí, A fondo pide volumen"],
  rans: 1,
  rwhy: "El ruido esconde el caso.",
  tip: "Project = reglas + archivo del caso.",
  items: ["Instrucciones arriba", "Knowledge corto", "El hilo no es el sistema"],
});

const research = t({
  id: "research",
  title: "Investigar: recorte, fuente, hueco",
  blurb: "ChatGPT busca si se lo pides. Tú contrastas.",
  hooks: [
    "Investigación en Coursiv no es “pregunta y copia”. Es acotar, pedir fuentes y etiquetar lo que no se pudo abrir.",
    "Sin país, año y para quién, te da el mundo. El mundo no se presenta el martes.",
  ],
  idea: "Acota. Pide enlaces o al menos nombres de fuente. Si no hay enlace, es pista. Dos fuentes si el dato mueve dinero.",
  bullets: [
    "País, año, audiencia",
    "Fuente a la vista",
    "Hueco etiquetado",
    "Tú abres el enlace cuando existe",
  ],
  q: "Un dato sin fuente en un brief estratégico, ¿qué es?",
  opts: ["Un KPI", "Una pista: se confirma o se baja a hipótesis", "Un insight premium"],
  ans: 1,
  why: "A fondo no publica rumores con formato ejecutivo.",
  fillTitle: "Acota la búsqueda",
  fillLead: "Tres recortes.",
  template: "Busca en {blank}, año {blank}, para {blank}. Lista fuentes.",
  answers: ["México", "2026", "pymes de comida"],
  slots: ["dónde", "cuándo", "quién"],
  sim: "Tres fuentes. Una sin fecha: hipótesis. Las otras dos se pueden abrir.",
  rq: "¿ChatGPT sustituye a Perplexity en este curso?",
  ropts: ["Sí, da igual", "No: aquí aprendes el oficio; Perplexity es otro cajón de Coursiv", "Sí si activas búsqueda"],
  rans: 1,
  rwhy: "Coursiv los lista aparte. El oficio de contrastar se parece; la herramienta no es la misma.",
  tip: "acota, fuente, hueco. Tú abres.",
  items: ["Recorte", "Pista ≠ hecho", "Dos fuentes si hay dinero"],
});

const gpts = t({
  id: "gpts",
  title: "GPTs de oficio, no de personalidad",
  blurb: "Un rol + archivos + lo que nunca debe hacer.",
  hooks: [
    "Un GPT “simpático” no es estratégico. Un GPT de research con veda de cifras inventadas sí.",
    "A fondo: el GPT es el molde. El chat es el caso de esta semana.",
  ],
  idea: "Nombre del oficio. Instrucciones cortas. Archivos del caso. Tres vetos. Prueba con un caso real, no con “hola”.",
  bullets: [
    "Oficio, no vibe",
    "Vetos visibles",
    "Archivos pocos y actuales",
    "Se prueba con un caso tuyo",
  ],
  q: "¿Qué hace útil un GPT de A fondo?",
  opts: ["Un chiste de arranque", "Rol, vetos y archivos del oficio", "Diez plugins", "Un avatar lindo"],
  ans: 1,
  why: "El oficio se reutiliza. La personalidad se agota.",
  fillTitle: "Define el GPT",
  fillLead: "Rol + veda.",
  template: "Eres {blank}. Nunca {blank}. Trabajas con {blank}.",
  answers: ["analista de research comercial", "inventar cifras", "el brief de la semana"],
  slots: ["rol", "veda", "archivo"],
  sim: "GPT de research. Veda de cifras. El brief se pega cada lunes.",
  rq: "¿El GPT reemplaza el pipeline de pasos?",
  ropts: ["Sí", "No: el GPT guarda el oficio; los pasos siguen numerados", "Sí si es GPT-5"],
  rans: 1,
  rwhy: "Herramienta + método. No una de las dos.",
  tip: "oficio, vetos, archivo. Luego el caso.",
  items: ["Sin vibe vacía", "Vetos arriba", "Se prueba con lo real"],
});

const canvas = t({
  id: "canvas",
  title: "Canvas: el documento se edita por bloques",
  blurb: "No pidas el artículo entero de un jalón si vas a cortar.",
  hooks: [
    "Trabajo estratégico suele vivir en un doc. Canvas (o el artefacto) se edita por sección. El globo de chat se reescribe entero y se te va el hilo.",
    "Pide un bloque. Márcalo. Pide el cambio de ese bloque.",
  ],
  idea: "Estructura primero (H1, secciones). Luego un bloque a la vez. “Mejora todo” revuelve lo que ya estaba bien.",
  bullets: [
    "Índice primero",
    "Un bloque por turno",
    "Di qué falló del bloque",
    "El resto se queda",
  ],
  q: "El segundo párrafo está largo. ¿Qué pides?",
  opts: ["Reescribe el doc", "Corta el segundo párrafo a 80 palabras; el resto igual", "Hazlo viral", "Cambia el tono de todo"],
  ans: 1,
  why: "El bloque. No el universo.",
  fillTitle: "Edita un bloque",
  fillLead: "El resto se queda.",
  template: "En la sección {blank}, recorta a {blank}. No toques {blank}.",
  answers: ["riesgos", "80 palabras", "la tesis"],
  slots: ["dónde", "tope", "veda"],
  sim: "Riesgos en 80. Tesis intacta. El resto igual.",
  rq: "¿Por qué no “mejóralo todo”?",
  ropts: ["Porque es grosero", "Porque revuelve lo que ya servía", "Por tokens"],
  rans: 1,
  rwhy: "Estratégico es cirugía. No demolición.",
  tip: "un bloque, un fallo, el resto quieto.",
  items: ["Índice primero", "Cirugía", "Nada de “mejora todo”"],
});

const datos = t({
  id: "datos",
  title: "Tablas y números con unidad",
  blurb: "Si hay cifra, hay unidad, rango y “por confirmar”.",
  hooks: [
    "ChatGPT no ve tu banco. Si pegas una tabla, di unidades. Si falta el dato, no lo redondee “para que se vea bien”.",
    "A fondo: el número mueve una decisión. Por eso se trata peor que un adjetivo.",
  ],
  idea: "Unidades al inicio. Vacío = vacío. Pide la tabla de salida con las mismas columnas. Nada de promedios de la industria si no los pegaste.",
  bullets: [
    "Unidad visible",
    "Hueco etiquetado",
    "Misma columnas de salida",
    "Tú contrastas la cifra gorda",
  ],
  q: "Falta el tipo de cambio en la tabla. ¿Qué sale?",
  opts: ["19.5 porque “es lo usual”", "Por confirmar", "Cero", "El de ayer en Twitter"],
  ans: 1,
  why: "A fondo no inventa FX.",
  fillTitle: "Declara números",
  fillLead: "Unidad y hueco.",
  template: "Ingresos en {blank}. Vacías = {blank}. No inventes {blank}.",
  answers: ["pesos MXN", "vacío", "tipo de cambio"],
  slots: ["unidad", "hueco", "veda"],
  sim: "Pesos. Huecos vacíos. FX = por confirmar.",
  rq: "¿Quién firma la cifra de la junta?",
  ropts: ["ChatGPT", "Tú", "El GPT"],
  rans: 1,
  rwhy: "El modelo recorta. La cifra se verifica.",
  tip: "unidad, hueco, veda de inventos.",
  items: ["Números con unidad", "Por confirmar a la vista", "Tú contrastas"],
});

const flujos = t({
  id: "flujos",
  title: "Un flujo que el equipo puede repetir",
  blurb: "Molde de pasos. Caso de la semana. Eso escala.",
  hooks: [
    "Automatizar en A fondo es el molde: research → cruce → página → huecos. El lunes pegas otro caso.",
    "Si cada vez reescribes el oficio, no hay sistema. Hay heroísmo.",
  ],
  idea: "Guarda el pipeline numerado. Variable = brief de la semana. Una persona revisa umbrales si el negocio cambió.",
  bullets: [
    "Pasos fijos",
    "Caso variable",
    "Misma salida",
    "Umbral se revisa",
  ],
  q: "¿Qué se reutiliza el lunes?",
  opts: ["El chat de marzo", "El pipeline numerado", "Nada", "El saludo"],
  ans: 1,
  why: "El caso cambia. El oficio no.",
  fillTitle: "Guarda el pipeline",
  fillLead: "Fijo vs semana.",
  template: "Fijo: {blank}. Variable: {blank}. Salida: {blank}.",
  answers: ["los 4 pasos", "el brief de la semana", "una página + huecos"],
  slots: ["molde", "caso", "entregable"],
  sim: "Pipeline listo. El lunes solo entra el brief nuevo.",
  rq: "Si ahora el comité pide 2 páginas, ¿qué actualizas?",
  ropts: ["Nada", "El molde de salida, a propósito", "El modelo"],
  rans: 1,
  rwhy: "El sistema se edita. No se ignora.",
  tip: "pasos fijos, caso de la semana.",
  items: ["Pipeline en un archivo", "Misma salida", "Umbral vivo"],
});

const memoria = t({
  id: "memoria",
  title: "Contexto que se pega, no que se adivina",
  blurb: "Memoria y Projects ayudan. El caso de esta semana se pega igual.",
  hooks: [
    "ChatGPT puede recordar preferencias. No recuerda el Excel de ayer si no lo pegas. A fondo no se fía de la memoria para cifras.",
    "Pega lo que mueve la decisión. El resto es ruido.",
  ],
  idea: "Preferencias de tono pueden vivir en el GPT. Cifras, nombres y plazos se pegan cada vez. “Ya sabes de qué te hablo” no es un brief.",
  bullets: [
    "Tono en instrucciones",
    "Cifras pegadas",
    "Nada de “ya sabes”",
    "El recorte del caso, no la biografía",
  ],
  q: "Un plazo que no pegaste, ¿de dónde sale?",
  opts: ["De la memoria mágica", "No sale: se pega o queda por confirmar", "Del GPT"],
  ans: 1,
  why: "A fondo no presenta plazos telepáticos.",
  fillTitle: "Separa tono y hechos",
  fillLead: "Qué se guarda, qué se pega.",
  template: "El tono vive en {blank}. Las cifras se {blank}. Nunca pidas que {blank}.",
  answers: ["las instrucciones", "pegan cada vez", "adivine el plazo"],
  slots: ["dónde", "hechos", "veda"],
  sim: "Tono guardado. Plazo pegado. Cero telepatía.",
  rq: "¿La memoria sustituye el Project?",
  ropts: ["Sí", "No: memoria es preferencia; Project es el caso", "Sí en Plus"],
  rans: 1,
  rwhy: "Dos cajones. No los fundas.",
  tip: "tono guardado. Hechos pegados.",
  items: ["Nada de “ya sabes”", "Cifras cada vez", "Project para el caso"],
});

const agentes = t({
  id: "agentes",
  title: "Tareas largas: tú pones el freno",
  blurb: "Un agente que no se revisa es un intern sin jefe.",
  hooks: [
    "ChatGPT puede encadenar pasos. A fondo no te pide que lo dejes solo con la marca o el dinero.",
    "Define el tope: cuántos pasos, qué puede tocar, qué te tiene que devolver para firmar.",
  ],
  idea: "Objetivo, herramientas permitidas, qué no puede hacer, entregable intermedio. Tú ves el intermedio. Luego el siguiente tramo.",
  bullets: [
    "Tope de pasos",
    "Qué no tocar",
    "Entregable intermedio",
    "Firma humana",
  ],
  q: "El agente ya “terminó” un brief de precios. ¿Se publica?",
  opts: ["Sí, para escalar", "No: revisas cifras y claims", "Sí si tardó mucho"],
  ans: 1,
  why: "Varios pasos no anulan la firma.",
  fillTitle: "Pon el freno",
  fillLead: "Tope y veda.",
  template: "Máximo {blank} pasos. No toques {blank}. Devuélveme {blank} antes de seguir.",
  answers: ["4", "precios finales", "la tabla de hallazgos"],
  slots: ["n", "veda", "intermedio"],
  sim: "4 pasos. Precios fuera. Tabla primero. Tú sigues.",
  rq: "¿Un agente sustituye el pipeline numerado?",
  ropts: ["Sí", "No: el agente corre tramos; el pipeline es el mapa que tú diseñaste", "Sí si se llama Agent"],
  rans: 1,
  rwhy: "La autonomía sin mapa es teatro.",
  tip: "tramos cortos, intermedio a la vista, tú firmas.",
  items: ["Tope", "Veda", "Revisión"],
});

const cierre = t({
  id: "cierre",
  title: "Cuándo no usar A fondo",
  blurb: "Un sticker, un mail de 6 líneas, un PDF de 40 páginas con citas.",
  hooks: [
    "Coursiv tiene ChatGPT diario, Perplexity, Claude: A fondo. Mezclarlos te cobra.",
    "Cierre: A fondo es pipeline e investigación en ChatGPT. No es todos los oficios.",
  ],
  idea: "Mail corto → ChatGPT diario. Fuentes a granel → Perplexity. Contrato largo con citas → Claude. Pipeline de research en ChatGPT → aquí.",
  bullets: [
    "Diario ≠ A fondo",
    "Perplexity para cazar enlaces",
    "Claude para el PDF delicado",
    "Tú reparte",
  ],
  q: "Un contrato de 40 páginas que no puede distorsionar, ¿dónde?",
  opts: ["ChatGPT: A fondo, porque “es estratégico”", "Claude: A fondo, con cita", "El ChatGPT diario", "Da igual"],
  ans: 1,
  why: "Coursiv puso Claude: A fondo para documentos. Este curso es otro oficio.",
  fillTitle: "Reparte",
  fillLead: "Tres cajones.",
  template: "El sticker va a {blank}. El pipeline de research a {blank}. El contrato a {blank}.",
  answers: ["ChatGPT diario", "ChatGPT: A fondo", "Claude: A fondo"],
  slots: ["corto", "pasos", "pdf"],
  sim: "Oficios partidos. Nadie le pide a A fondo que cite la cláusula 4.2 como si fuera Claude.",
  rq: "¿Terminar A fondo sustituye los otros cursos?",
  ropts: ["Sí", "No: 12 lecciones de este oficio, no de todos", "Sí, el diploma es universal"],
  rans: 1,
  rwhy: "Los números del catálogo son distintos a propósito.",
  tip: "pipeline aquí. Diario, Perplexity y Claude, sus cajones.",
  items: ["12 / 4 h", "Varios pasos + research", "Tú firmas"],
});

export const chatgptFondoUnits = units([
  ["u1", "El sistema, no el soplo", [vs, pasos, projects, research]],
  ["u2", "Herramientas del oficio", [gpts, canvas, datos, flujos]],
  ["u3", "Límites", [memoria, agentes, cierre]],
]);
