import { quick, units } from "./pack.js";

const C = "Claude";
const S = "docs";

function t(spec) {
  return quick({ brand: C, scene: S, ...spec });
}

const hoja = t({
  id: "hoja",
  title: "Claude no abre tu Excel",
  blurb: "Pegas la tabla. Claude razona. Excel sigue siendo Excel.",
  hooks: [
    "Coursiv pone Claude para Excel en 7 lecciones y 3 horas: trabajo estratégico, análisis de hojas y automatización. No es un plugin que reescribe el archivo. Es un analista al que le pegas un recorte.",
    "Si pides “analiza mi Excel” sin columnas, inventa nombres. Si pegas encabezados y 20 filas reales, puede hablar de márgenes, huecos y la siguiente pregunta.",
  ],
  idea: "Copia el rango con encabezado. Di qué pregunta el negocio. Pide la respuesta en tabla, no en ensayo. Luego tú pegas la fórmula o el filtro en Excel.",
  bullets: [
    "Encabezados visibles: mes, SKU, canal, pesos",
    "Una pregunta de negocio, no “dame insights”",
    "Salida: tabla o pasos, no un ladrillo",
    "Tú aplicas el cambio en la hoja",
  ],
  q: "¿Claude edita el .xlsx por ti?",
  opts: ["Sí, si se lo pides bonito", "No: razona sobre el recorte que pegas", "Solo en Mac", "Solo si hay pivot"],
  ans: 1,
  why: "La hoja se queda en Excel. Claude acelera el análisis.",
  fillTitle: "Arma el recorte",
  fillLead: "Encabezado + pregunta.",
  template: "Pego columnas {blank}. Pregunto {blank}. Quiero la respuesta en {blank}.",
  answers: ["mes, canal, ingresos", "qué canal cayó en marzo", "tabla"],
  slots: ["columnas", "pregunta", "formato"],
  sim: "Marzo: canal retail −18%. Online +4%. El hueco está en 3 SKUs, no en todo el canal.",
  rq: "¿Qué falta si solo pegas números sin encabezado?",
  ropts: ["Nada", "Claude no sabe qué es cada columna y mezcla escalas", "Más tokens"],
  rans: 1,
  rwhy: "Sin nombre de columna, el análisis es un cuento.",
  tip: "pega el recorte con encabezado. Una pregunta. Tabla de vuelta.",
  items: ["Excel sigue en Excel", "Encabezados primero", "Una pregunta de negocio"],
});

const encabezados = t({
  id: "encabezados",
  title: "Encabezados, unidades y el recorte",
  blurb: "Pesos no son porcentajes. Di la unidad antes del caso.",
  hooks: [
    "Una columna que se llama “valor” puede ser precio, margen o índice. Claude mezcla si no se lo dices.",
    "El recorte no tiene que ser el libro entero. 30 filas del caso + el encabezado alcanzan para un primer corte.",
  ],
  idea: "Nombra cada columna y su unidad. Di si hay filtros ya aplicados. Si hay celdas vacías, dilo: no las rellene.",
  bullets: [
    "Nombre + unidad en la primera línea",
    "Filtro que ya aplicaste",
    "Vacíos = vacío, no cero",
    "No pegas 40 mil filas “por si acaso”",
  ],
  q: "Una celda vacía, ¿qué le dices a Claude?",
  opts: ["Que ponga el promedio", "Que la deje vacía y no invente", "Que la trate como 0", "Que la borre del análisis"],
  ans: 1,
  why: "Inventar un 0 cambia el promedio. El hueco se etiqueta.",
  fillTitle: "Declara unidades",
  fillLead: "Antes del caso.",
  template: "Columna Ingreso está en {blank}. Vacías = {blank}. Ya filtré {blank}.",
  answers: ["pesos MXN", "vacío, no cero", "solo 2026"],
  slots: ["unidad", "vacíos", "filtro"],
  sim: "Unidades fijas. No relleno huecos. El corte es 2026.",
  rq: "¿Por qué no pegar el libro entero?",
  ropts: ["Por tokens de moda", "Porque el ruido esconde el caso", "Porque Excel se ofende"],
  rans: 1,
  rwhy: "El recorte del caso se puede checar. El libro entero, no.",
  tip: "unidad, vacíos y filtro. Luego el caso.",
  items: ["Nombre de columna", "Unidad visible", "Hueco ≠ cero"],
});

const pregunta = t({
  id: "pregunta",
  title: "Preguntas que se ven en celdas",
  blurb: "Si no se puede señalar la fila, no es un hallazgo.",
  hooks: [
    "“¿Cómo vamos?” no se verifica. “¿Qué 5 SKUs bajaron más de 10% vs el mes previo?” sí: se señala la fila.",
    "Coursiv insiste en trabajo estratégico: la pregunta mueve una decisión, no un dashboard bonito.",
  ],
  idea: "Pide el top N, el umbral y la comparación. Luego: “señala la fila o el SKU”. Si no puede, es hipótesis.",
  bullets: [
    "Comparación explícita (vs mes, vs meta)",
    "Umbral (más de 10%, menos de X)",
    "Top N, no “los importantes”",
    "Ancla: SKU, canal o celda",
  ],
  q: "¿Cuál pregunta se puede checar en la hoja?",
  opts: [
    "Dame insights de negocio",
    "Lista los 5 SKUs con caída >10% vs febrero y la fila",
    "Hazlo estratégico",
    "Resume el Excel",
  ],
  ans: 1,
  why: "Hay umbral, N y ancla. Se abre la fila.",
  fillTitle: "Hazla verificable",
  fillLead: "N, umbral, ancla.",
  template: "Top {blank} canales con caída mayor a {blank} vs {blank}. Señala la fila.",
  answers: ["5", "10%", "febrero"],
  slots: ["N", "umbral", "base"],
  sim: "1) Retail −18% (filas 12-14). 2) Mayoreo −11% (fila 22). El resto bajo el umbral.",
  rq: "Si Claude no puede señalar la fila, ¿qué es el dato?",
  ropts: ["Un KPI oficial", "Hipótesis: vuelves a la hoja", "Un insight premium"],
  rans: 1,
  rwhy: "Sin ancla, no se presenta al equipo.",
  tip: "N + umbral + “señala la fila”.",
  items: ["Una comparación", "Un número de corte", "Una ancla"],
});

const formulas = t({
  id: "formulas",
  title: "Fórmulas vs prosa",
  blurb: "Si va a la celda, pide la fórmula. Si va al mail, pide prosa.",
  hooks: [
    "Claude puede proponerte un SUMIFS. También puede narrar el trimestre. No pidas las dos cosas en el mismo soplo si no dices cuál pegarás.",
    "La fórmula se prueba en una celda. La prosa se prueba con el jefe. Oficios distintos.",
  ],
  idea: "Di: “quiero la fórmula para Excel en español, con nombres de columna”. O: “quiero 4 viñetas para el comité, sin fórmula”. Mezclarlas ensucia ambos.",
  bullets: [
    "Fórmula: función, rangos, qué hacer con vacíos",
    "Prosa: para quién y cuántas líneas",
    "No “explícame y además dame el VBA” en el mismo pedido si no lo necesitas",
    "Tú pegas y pruebas. Claude no ve el error de referencia",
  ],
  q: "¿Qué pides si el entregable es una celda?",
  opts: ["Un ensayo del trimestre", "La fórmula y un ejemplo con 3 filas", "Un dashboard en ASCII", "Que la publique en Sheets"],
  ans: 1,
  why: "Se pega y se prueba. El ensayo no entra en C2.",
  fillTitle: "Separa oficios",
  fillLead: "Celda o comité.",
  template: "Para la celda quiero {blank}. Para el comité, {blank} viñetas. No mezcles {blank}.",
  answers: ["la fórmula SUMIFS", "4", "VBA"],
  slots: ["fórmula", "prosa", "extra"],
  sim: "SUMIFS listo con ejemplo. 4 viñetas aparte. Sin macros.",
  rq: "¿Quién prueba la fórmula?",
  ropts: ["Claude, en silencio", "Tú, en una celda de prueba", "El pivot"],
  rans: 1,
  rwhy: "La referencia rota se ve en Excel, no en el chat.",
  tip: "fórmula o prosa. Di cuál se pega dónde.",
  items: ["Un entregable por pedido", "Ejemplo de 3 filas", "Tú pruebas la celda"],
});

const escenario = t({
  id: "escenario",
  title: "Escenarios, no un solo número",
  blurb: "Base, upside, downside. El Excel aguanta tres columnas.",
  hooks: [
    "Automatización empresarial no es “un total”. Es poder cambiar un supuesto y ver qué pasa.",
    "Pide a Claude que deje visibles los supuestos. Si el 12% de inflación va escondido en la prosa, no se puede tocar.",
  ],
  idea: "Tres escenarios con los mismos encabezados. Un supuesto por fila. Qué cambia y qué se queda fijo. Luego tú armas las columnas en la hoja.",
  bullets: [
    "Supuestos nombrados (precio, volumen, tipo de cambio)",
    "Qué es fijo vs qué se mueve",
    "Misma estructura en los tres cortes",
    "Sin “en un mundo ideal” sin número",
  ],
  q: "¿Qué hace útil un escenario?",
  opts: ["Más adjetivos", "Supuestos visibles que puedes cambiar en la hoja", "Un solo total redondo", "Un gráfico en el chat"],
  ans: 1,
  why: "Si no se puede tocar el supuesto, no es un modelo. Es un cuento.",
  fillTitle: "Tres cortes",
  fillLead: "Mismo molde.",
  template: "Base: {blank}. Downside: {blank}. Lo fijo es {blank}.",
  answers: ["volumen actual", "volumen −15%", "precio de lista"],
  slots: ["base", "peor", "fijo"],
  sim: "Tres columnas, un precio. Solo mueve volumen. El comité ve el rango, no un milagro.",
  rq: "¿Dónde viven los supuestos?",
  ropts: ["En un adjetivo", "En celdas que tú puedes editar", "En la memoria del chat"],
  rans: 1,
  rwhy: "El chat se olvida. La celda no.",
  tip: "tres escenarios, supuestos a la vista.",
  items: ["Base / up / down", "Un supuesto por fila", "La hoja es el modelo"],
});

const reporte = t({
  id: "reporte",
  title: "El reporte semanal que se puede repetir",
  blurb: "Mismo molde. Otras filas. Eso es automatizar.",
  hooks: [
    "Coursiv habla de automatización empresarial: no un macro mágico. Un pedido que el lunes se vuelve a pegar.",
    "Guarda el molde: columnas, umbrales, formato de salida. Cada semana solo cambia el recorte.",
  ],
  idea: "Un bloque fijo (“estas columnas, este umbral, esta tabla de salida”) y un bloque variable (el pegado de la semana). Si cada lunes reescribes el oficio, no hay automatización.",
  bullets: [
    "Molde en un archivo o Project",
    "El recorte de la semana se pega debajo",
    "Misma tabla de salida",
    "Una persona revisa el umbral si el negocio cambió",
  ],
  q: "¿Qué se reutiliza el lunes?",
  opts: ["El chat entero de marzo", "El molde: columnas, umbral y formato", "Un prompt de Twitter", "Nada, se improvisa"],
  ans: 1,
  why: "El recorte cambia. El oficio no.",
  fillTitle: "Guarda el molde",
  fillLead: "Fijo vs de la semana.",
  template: "Fijo: {blank} y umbral {blank}. Variable: {blank} de esta semana.",
  answers: ["columnas mes-canal-ingreso", "10%", "el recorte"],
  slots: ["columnas", "corte", "pegado"],
  sim: "Molde listo. El lunes solo pegas marzo. La tabla sale igual.",
  rq: "Si el umbral del negocio cambió, ¿qué haces?",
  ropts: ["Nada, el molde es sagrado", "Actualizas el umbral a propósito", "Pides “más magia”"],
  rans: 1,
  rwhy: "Automatizar no es congelar una regla vieja.",
  tip: "molde fijo, recorte de la semana. Eso escala.",
  items: ["Un archivo del pedido", "Misma salida", "Umbral se revisa"],
});

const limites = t({
  id: "limites",
  title: "Lo que Claude no ve de tu libro",
  blurb: "Hojas ocultas, nombres definidos y el archivo de 40 MB.",
  hooks: [
    "No ve macros, no ve Power Query, no ve la hoja que no pegaste. Si el dato vive en otra pestaña, no existe para el chat.",
    "Cierre de la ruta: Excel sigue siendo el sistema. Claude es el analista de guardia sobre el recorte.",
  ],
  idea: "Lista lo que NO pegaste. Pide que no invente hojas. Si hay un cruce con un CRM, dilo: “no está en esta tabla”.",
  bullets: [
    "Lo no pegado no existe",
    "No inventar catálogos ni tipos de cambio",
    "Fórmulas complejas: se prueban en una celda",
    "Datos personales: recorta antes de pegar",
  ],
  q: "Claude dice un tipo de cambio que no está en la hoja. ¿Qué es?",
  opts: ["Un dato oficial", "Una invención: se marca o se pega el tipo real", "Un KPI de Claude Pro"],
  ans: 1,
  why: "Si no estaba en el recorte, no se presenta.",
  fillTitle: "Declara el hueco",
  fillLead: "Lo que no está.",
  template: "No pegué {blank}. No inventes {blank}. El tipo de cambio va {blank}.",
  answers: ["la hoja de costos", "el catálogo", "por confirmar"],
  slots: ["faltante", "veda", "dato"],
  sim: "Hueco etiquetado. Sin catálogo fantasma. Tipo de cambio = por confirmar.",
  rq: "¿Quién firma el número que sale en la junta?",
  ropts: ["Claude", "Tú, con la hoja a la vista", "El prompt"],
  rans: 1,
  rwhy: "La ruta acelera el corte. La firma es tuya.",
  tip: "lo no pegado no existe. Excel firma. Claude recorta.",
  items: ["Declara huecos", "No inventar FX ni catálogos", "Tú pegas el número"],
});

export const claudeExcelUnits = units([
  ["u1", "La hoja y el recorte", [hoja, encabezados, pregunta]],
  ["u2", "De la celda al reporte", [formulas, escenario, reporte, limites]],
]);
